### ISSUE TITLE
 "errorMessage": "Cannot convert undefined or null to object",

### ISSUE THREAD

**Issue by Neferpitooou** [probot/adapter-aws-lambda-serverless#129]
{
  "errorType": "TypeError",
  "errorMessage": "Cannot convert undefined or null to object",
  "trace": [
    "TypeError: Cannot convert undefined or null to object",
    "    at Function.entries (<anonymous>)",
    "    at module.exports (/var/task/node_modules/lowercase-keys/index.js:5:36)",
    "    at lambdaFunction (/var/task/node_modules/@probot/adapter-aws-lambda-serverless/lambda-function.js:19:28)",
    "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"
  ]
}

My probot lambda function is having issue above.

**Comment by wolfy1339** [comment]
Can you please share some code demonstrating your issue?

**Comment by ad-zsolt-imre** [comment]
I'm struggling with the same, I have the below sample code:

```typescript
import { Probot } from "probot";
import { createLambdaFunction, createProbot } from "@probot/adapter-aws-lambda-serverless";

const app = (app: Probot) => {
    app.log.info("TODO");
};

export const handler = async (event: any, context: any) => {
    return createLambdaFunction(app, { probot: createProbot() })(event, context);
};
```

I bundle the code as:

```
npx esbuild src/index.ts --bundle --format=cjs --platform=node --target=node20 --outfile=dist/index.js --external:aws-sdk
```

**Comment by ad-zsolt-imre** [comment]
I made some progress in my investigation. So, what I was trying to do:

 1. Create lambda function on AWS UI with Function URL that requires no authentication
 2. Upload the bundled probot JS code via the UI
 3. Go to the Test tab and run a test to see what happens

However, then payload sent to the lambda function during the test was not an HTTP event but an example object. I switched the test payload to the API Gateway HTTP API template which is an object that had the HTTP headers (expected by the lambda-function) so I got a different but reasonably expected error:

Snippet:

```
{
  "errorType": "AggregateError",
  "errorMessage": "\n    Error: [@octokit/webhooks] signature does not match event payload and secret\n        at verifyAndReceive 
...
```
 
So, so far my conclusion is that I may be able to work may way through and get it working. But, from the `adapter-aws-lambda-serverless` lib perspective, better documentation and more importantly, better error handling and meaningful error messages would greatly improve the developer experience.
